### ISSUE TITLE
Fresh Install, can't start

### ISSUE THREAD

**Issue by Chico0008** [Jarli01/xenorchestra_installer#127]
Hi

I'm testing XCP-NG, si XCP is installed on a R630server using local disk for now.

I created a Ubuntu 22.04 server, and wanted ton install XOCE using the install.sh script mentionned in main page.

Everything terminated ok, bu Xo-server won't start.

**Confirm XOCE services are running**
```
root@xoce:~# systemctl status xo-server.service
× xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2024-11-27 13:50:32 CET; 2min 12s ago
    Process: 1818 ExecStart=/usr/local/bin/node ./dist/cli.mjs (code=exited, status=1/FAILURE)
   Main PID: 1818 (code=exited, status=1/FAILURE)
        CPU: 79ms

nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
nov. 27 13:50:32 xoce systemd[1]: Stopped XO Server.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Start request repeated too quickly.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:32 xoce systemd[1]: Failed to start XO Server.
root@xoce:~#
```

**Provide the output of journalctl logs**
```
root@xoce:~# journalctl -u xo-server -f -n 50
nov. 27 13:50:31 xoce xo-server[1804]: internal/modules/cjs/loader.js:818
nov. 27 13:50:31 xoce xo-server[1804]:   throw err;
nov. 27 13:50:31 xoce xo-server[1804]:   ^
nov. 27 13:50:31 xoce xo-server[1804]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
nov. 27 13:50:31 xoce xo-server[1804]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
nov. 27 13:50:31 xoce xo-server[1804]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
nov. 27 13:50:31 xoce xo-server[1804]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
nov. 27 13:50:31 xoce xo-server[1804]:     at internal/main/run_main_module.js:17:47 {
nov. 27 13:50:31 xoce xo-server[1804]:   code: 'MODULE_NOT_FOUND',
nov. 27 13:50:31 xoce xo-server[1804]:   requireStack: []
nov. 27 13:50:31 xoce xo-server[1804]: }
nov. 27 13:50:31 xoce systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
nov. 27 13:50:31 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:31 xoce systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 3.
nov. 27 13:50:31 xoce systemd[1]: Stopped XO Server.
nov. 27 13:50:31 xoce systemd[1]: Started XO Server.
nov. 27 13:50:32 xoce xo-server[1811]: internal/modules/cjs/loader.js:818
nov. 27 13:50:32 xoce xo-server[1811]:   throw err;
nov. 27 13:50:32 xoce xo-server[1811]:   ^
nov. 27 13:50:32 xoce xo-server[1811]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
nov. 27 13:50:32 xoce xo-server[1811]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
nov. 27 13:50:32 xoce xo-server[1811]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
nov. 27 13:50:32 xoce xo-server[1811]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
nov. 27 13:50:32 xoce xo-server[1811]:     at internal/main/run_main_module.js:17:47 {
nov. 27 13:50:32 xoce xo-server[1811]:   code: 'MODULE_NOT_FOUND',
nov. 27 13:50:32 xoce xo-server[1811]:   requireStack: []
nov. 27 13:50:32 xoce xo-server[1811]: }
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
nov. 27 13:50:32 xoce systemd[1]: Stopped XO Server.
nov. 27 13:50:32 xoce systemd[1]: Started XO Server.
nov. 27 13:50:32 xoce xo-server[1818]: internal/modules/cjs/loader.js:818
nov. 27 13:50:32 xoce xo-server[1818]:   throw err;
nov. 27 13:50:32 xoce xo-server[1818]:   ^
nov. 27 13:50:32 xoce xo-server[1818]: Error: Cannot find module '/opt/xen-orchestra/packages/xo-server/dist/cli.mjs'
nov. 27 13:50:32 xoce xo-server[1818]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
nov. 27 13:50:32 xoce xo-server[1818]:     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
nov. 27 13:50:32 xoce xo-server[1818]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
nov. 27 13:50:32 xoce xo-server[1818]:     at internal/main/run_main_module.js:17:47 {
nov. 27 13:50:32 xoce xo-server[1818]:   code: 'MODULE_NOT_FOUND',
nov. 27 13:50:32 xoce xo-server[1818]:   requireStack: []
nov. 27 13:50:32 xoce xo-server[1818]: }
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
nov. 27 13:50:32 xoce systemd[1]: Stopped XO Server.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Start request repeated too quickly.
nov. 27 13:50:32 xoce systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 13:50:32 xoce systemd[1]: Failed to start XO Server.
```

**Provide answers to these questions:**
* Is this a fresh install or an upgrade? > Fresh
* Version of XOCE server and web interface you're running > Last available i suppose
* What OS is XOCE running on? Ubuntu Server 22.04
* A link to the ISO you've used as as the server (so we can verify/troubleshoot) > 
* What method did you use to install XOCE (xo_install.sh, manual installation, etc) > https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh

**Comment by Jarli01** [comment]
I have to download the ISO you're using, it'll take a bit before I can update this.

**Comment by Chico0008** [comment]
Tkin my Vm wass a mess.
i just reinstall a clean ubuntu 22.04
then tried reinstall using the script

no i got another error : 
```
nov. 27 14:52:20 s-esx1 systemd[1]: Started XO Server.
nov. 27 14:52:20 s-esx1 systemd[734]: xo-server.service: Changing to the requested working directory failed: No such file or directory
nov. 27 14:52:20 s-esx1 systemd[734]: xo-server.service: Failed at step CHDIR spawning /usr/local/bin/node: No such file or directory
nov. 27 14:52:20 s-esx1 systemd[1]: xo-server.service: Main process exited, code=exited, status=200/CHDIR
nov. 27 14:52:20 s-esx1 systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 14:52:20 s-esx1 systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
nov. 27 14:52:20 s-esx1 systemd[1]: Stopped XO Server.
nov. 27 14:52:20 s-esx1 systemd[1]: xo-server.service: Start request repeated too quickly.
nov. 27 14:52:20 s-esx1 systemd[1]: xo-server.service: Failed with result 'exit-code'.
nov. 27 14:52:20 s-esx1 systemd[1]: Failed to start XO Server.
```
```
dsi@s-esx1:~$ ll /usr/local/bin/node
-rwxr-xr-x 1 root root 117383456 nov.  27 14:46 /usr/local/bin/node*
dsi@s-esx1:~$
```

**Comment by Jarli01** [comment]
Glad to know that it worked out, and sorry for the delay (it's a work day here). 

Marking this as closed.
