### ISSUE TITLE
xoa not working after update with cli

### ISSUE THREAD

**Issue by BerT666** [Jarli01/xenorchestra_installer#76]
**Describe the bug**
After updating (  curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f ) the WebGUI does not load. tried to do this several times within the last week.

**To Reproduce**
1. update using " curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -f"
2. restart server
3. try to access the WebGUI Page => site not found
4. regarding netstat, the Webserver does not start at all

**Expected behavior**
The Login Page should be accessible after updating

**Desktop/Server details (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Browser [tested with Chrome, Firefox and Edge; each with latest patch level]

**Confirm XOCE services are running**
root@xoa:/home/tb# systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Tue 2020-05-26 08:41:52 UTC; 8s ago
  Process: 19909 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=0/SUCCESS)
 Main PID: 19909 (code=exited, status=0/SUCCESS)

Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Mai 26 08:41:52 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Failed with result 'start-limit-hit'.
Mai 26 08:41:52 xoa systemd[1]: Failed to start XO Server.

**Provide the output of journalctl logs**
-- Logs begin at Sun 2020-03-15 21:36:31 UTC. --
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.load (module.js:566:32)
Mai 26 08:41:51 xoa xo-server[19874]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:51 xoa xo-server[19874]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.require (module.js:597:17)
Mai 26 08:41:51 xoa xo-server[19874]:     at require (internal/module.js:11:18)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/index.js:35:1)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.load (module.js:566:32)
Mai 26 08:41:51 xoa xo-server[19874]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:51 xoa xo-server[19874]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module.require (module.js:597:17)
Mai 26 08:41:51 xoa xo-server[19874]:     at require (internal/module.js:11:18)
Mai 26 08:41:51 xoa xo-server[19874]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo.js:17:1)
Mai 26 08:41:51 xoa xo-server[19874]:     at Module._compile (module.js:653:30) code: 'MODULE_NOT_FOUND' } }
Mai 26 08:41:51 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:51 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 4.
Mai 26 08:41:51 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:51 xoa systemd[1]: Started XO Server.
Mai 26 08:41:52 xoa xo-server[19909]: 2020-05-26T08:41:52.352Z xo:xo-server ERROR uncaught exception { error: { Error: Cannot find module 'openpgp'
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._resolveFilename (module.js:548:15)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:475:25)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/config-management.js:1:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.load (module.js:566:32)
Mai 26 08:41:52 xoa xo-server[19909]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/index.js:35:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.Module._extensions..js (module.js:664:10)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.load (module.js:566:32)
Mai 26 08:41:52 xoa xo-server[19909]:     at tryModuleLoad (module.js:506:12)
Mai 26 08:41:52 xoa xo-server[19909]:     at Function.Module._load (module.js:498:3)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module.require (module.js:597:17)
Mai 26 08:41:52 xoa xo-server[19909]:     at require (internal/module.js:11:18)
Mai 26 08:41:52 xoa xo-server[19909]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/src/xo.js:17:1)
Mai 26 08:41:52 xoa xo-server[19909]:     at Module._compile (module.js:653:30) code: 'MODULE_NOT_FOUND' } }
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 5.
Mai 26 08:41:52 xoa systemd[1]: Stopped XO Server.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Start request repeated too quickly.
Mai 26 08:41:52 xoa systemd[1]: xo-server.service: Failed with result 'start-limit-hit'.
Mai 26 08:41:52 xoa systemd[1]: Failed to start XO Server.

**Provide answers to these questions:**
* Is is an upgrade?
* Version of XOCE server and web interface you're running: 5.59.0
* What OS is XOCE running on? : Ubuntu 18.04 LTS (latest patches installed)
* What method did you use to install XOCE: xo_install.sh
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error: LoginPage

* Indicate whether or not you've manually edited any data directly. : Not edited any data

**Comment by Jarli01** [comment]
Do you have a subscription with the XO team? If so please reach out to the vates team.

You're mixing up the possible issues here, the installation script is for specifically installing XO(Community edition) onto a clean host.

Please let us know

**Comment by Jarli01** [comment]
I've just pushed a pull request through for python3-minimal, please try the installation again. If that doesn't work, please try a more current OS, 18.04 is very old.
